name: 'skidamarink'

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build the tagged Docker image
              run: docker build . --tag foobar
            - name: Run a privileged container
              run: docker run --privileged foobar echo fjong
            - name: whoami
              run: whoami
            - name: kvm
              run: ls -la /dev/kvm
